### ISSUE TITLE
netifaces latest version (0.10.4) is not Python 3 compatible

### ISSUE THREAD

**Issue by do3cc** [infothrill/python-dyndnsc#15]
This is an upstream issue.
I created a pull request but did not validate if this is enough:
https://bitbucket.org/al45tair/netifaces/pull-request/2/fix-error-preventing-to-install-netifaces/diff

This is the reason why tox can't do python 3 tests.
If it works locally, this is because on pypi are also binary packages of netifaces, these do not have the setup.py any more. Don't know when binary packages get used by installers, I never use them.

**Comment by infothrill** [comment]
The python package dyndnsc is now independent of netifaces, however it will still expose the functionality if it is installed. Since the formal dependency is gone, I think we can consider this ticket resolved even if the upstream issue persists.
