### ISSUE TITLE
Improve diagnostics

### ISSUE THREAD

**Issue by bronger** [infothrill/python-dyndnsc#57]
I recommend to add another Python matra to the bottom of http://dyndnsc.readthedocs.org/en/latest/dev/contrib.html#idioms-to-keep-in-mind: "Errors should never pass silently".  ;-)

Currently, I try to update an IP using dyndns2 and nothing is updated -- but no exception occurs either.  Just for the record, the code is:

```
    updater = dyndns2.UpdateProtocolDyndns2("juliabase.de", "351585", "XXX", 
                                            "http://carol.selfhost.de")
    updater.update(ip)
```

**Comment by infothrill** [comment]
@bronger I believe the last commit fixes the issue you faced
